WORLD_NAME: "reInvent2019_track"
CHANGE_START_POSITION: true
ALTERNATE_DRIVING_DIRECTION: false
NUMBER_OF_OBSTACLES: 0
IS_OBSTACLE_BOT_CAR: false
RANDOMIZE_OBSTACLE_LOCATIONS: false
IS_LANE_CHANGE: true
LOWER_LANE_CHANGE_TIME: 3.0
UPPER_LANE_CHANGE_TIME: 5.0
LANE_CHANGE_DISTANCE: 1.0
NUMBER_OF_BOT_CARS: 3
MIN_DISTANCE_BETWEEN_BOT_CARS: 2.0
RANDOMIZE_BOT_CAR_LOCATIONS: true
BOT_CAR_SPEED: 0.2
ENABLE_DOMAIN_RANDOMIZATION: false
MAX_EPISODE_STEPS: 10000
SEED: 999
