environment: "deepracer-v0"
experiment_name: "smile_track"
total_timesteps: 15000
lr: 0.0003
gamma: 0.99
batch_size: 64
epoch_k: 10
clip_eps: 0.2
ent_coef: 0.01
seed: 42
pretrained_path: "saved_models_part1/model_smile_track.pt"

